import { ApiAnimalType } from "@/types/animal";
import { ApiEmotion } from "@/types/Emotion";
import { IPostSummaryData } from "@/types/PostSummaryData";

export const dummyPosts: IPostSummaryData[] = [
  {
    id: 3,
    userId: 1,
    nickname: "TestUser",
    profileImageUrl: "",
    transformedContent: "이것은 첫 번째 게시글의 변환된 내용입니다.",
    thumbnailUrl:
      "https://blog.kakaocdn.net/dn/nIxZe/btq8aZUDa8c/0pZCTurE0TUPFu9Dq5u8K0/img.jpg",
    emotion: ApiEmotion.HAPPY,
    postType: ApiAnimalType.CAT,
    likeCount: 12,
    commentCount: 3,
    createdAt: "2025-04-28 20:37:42",
    updatedAt: "2025-04-28 20:37:42",
  },
  {
    id: 4,
    userId: 1,
    nickname: "TestUser",
    profileImageUrl: "",
    transformedContent: "이것은 두 번째 게시글의 변환된 내용입니다.",
    thumbnailUrl: "",
    emotion: ApiEmotion.SAD,
    postType: ApiAnimalType.DOG,
    likeCount: 0,
    commentCount: 0,
    createdAt: "2025-04-28 20:37:42",
    updatedAt: "2025-04-28 20:37:42",
  },
  {
    id: 5,
    userId: 1,
    nickname: "TestUser",
    profileImageUrl: "",
    transformedContent: "이것은 세 번째 게시글의 변환된 내용입니다.",
    thumbnailUrl: "",
    emotion: ApiEmotion.NONE,
    postType: ApiAnimalType.CAT,
    likeCount: 0,
    commentCount: 0,
    createdAt: "2025-04-28 20:37:42",
    updatedAt: "2025-04-28 20:37:42",
  },
  {
    id: 6,
    userId: 1,
    nickname: "TestUser",
    profileImageUrl: "",
    transformedContent: "이것은 네 번째 게시글의 변환된 내용입니다.",
    thumbnailUrl: "",
    emotion: ApiEmotion.ANGRY,
    postType: ApiAnimalType.CAT,
    likeCount: 0,
    commentCount: 0,
    createdAt: "2025-04-28 20:37:42",
    updatedAt: "2025-04-28 20:37:42",
  },
];
